


# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
---
include:
  - board: nice_nano_v2
    shield: do52pro_tp_left
  - board: nice_nano_v2
    shield: do52pro_tp_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  # Settings Reset firmware
  # This will build a firmware that can wipe all settings from your
  # controller. It's useful when you have bluetooth issues or when your split
  # keyboard halfs are not pairing.
  #
  # More info:
  # https://zmk.dev/docs/troubleshooting#split-keyboard-halves-unable-to-pair
  - board: nice_nano_v2
    shield: settings_reset